### ISSUE TITLE
map或许会导致主程序闪退

### ISSUE THREAD

**Issue by Logiase** [yguilai/CleverQQ-SDK-Golang#1]
不知道大佬能不能多测试一下map
貌似map初始化会让主程序闪退

**Comment by yguilai** [comment]
能将具体问题复现一下吗

**Comment by yguilai** [comment]
@Logiase 请复现一下问题

**Comment by yguilai** [comment]
你应该使用make()初始化map, 另外主程序闪退可能是因为程序`panic`, 尝试使用`recover`捕获panic并通过`IROutPutLog()`输出到框架日志, 以便观察问题

**Comment by Logiase** [comment]
抱歉，是我疏忽了，刚才尝试重启服务器这个问题就解决了

**Comment by yguilai** [comment]
目前我已给`IR_Event`事件添加recover捕获异常, 默认情况下它是关闭的, 需要设置`clvq.OnRecover = true`以启用此功能, 其他三个事件是否添加还在考虑. 如果你有其他建议/问题, 欢迎提出!
